### ISSUE TITLE
No letter-of-credit application with ID undefined found.

### ISSUE THREAD

**Issue by ice09** [corda/LetterOfCredit#13]
While trying out the demo, in the 3rd step () this message prevents LoC approval by the bank:
`No letter-of-credit application with ID undefined found.`

**Comment by joeldudleyr3** [comment]
Did you run the demo as per the instructions here: https://www.youtube.com/watch?v=PUpO9VEieB4? Are you auto-completing the forms at each stage?

**Comment by ice09** [comment]
No, I didn't. Thanks, will check this and report here or just close.

**Comment by ice09** [comment]
I applied the steps now exactly as noted in the video, but the error remains the same. Also, the animations shown in the video are not present if I try it myself.
The exception in the Corda-App is
```
[INFO ] 23:13:57,610 [Node thread-2] (NodeVaultService.kt:381) vault.NodeVaultService._queryBy - Vault Query for contract type: class eloc.state.LetterOfCreditApplicationState, criteria: VaultQueryCriteria(status=UNCONSUMED, contractStateTypes=null, stateRefs=null, notary=null, softLockingCondition=null, timeCondition=null), pagination: PageSpecification(pageNumber=-1, pageSize=200), sorting: Sort(columns=[]) {}
[WARN ] 23:13:57,628 [Node thread-2] (FlowStateMachineImpl.kt:111) flow.[4c59e5ea-ed42-4b37-abaa-22216516070b].run - Terminated by unexpected exception {}
java.lang.IllegalArgumentException: No letter-of-credit application with ID undefined found.
	at eloc.flow.ApproveLoCFlow.call(ApproveLoCFlow.kt:40) ~[kotlin-source-0.1.jar:?]
	at eloc.flow.ApproveLoCFlow.call(ApproveLoCFlow.kt:21) ~[kotlin-source-0.1.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:96) [corda-node-corda-3.0.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:44) [corda-node-corda-3.0.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:62) [corda-node-corda-3.0.jar:?]
```

**Comment by ice09** [comment]
Also this might be important, in step 2:

![image](https://user-images.githubusercontent.com/2828581/42784346-34a5ecc6-894f-11e8-804d-3cc175e4dc67.png)

**Comment by ice09** [comment]
This link for approve is wrong: http://localhost:10007/api/loc/approve-loc?ref=undefined
If I manually correct it to http://localhost:10007/api/loc/approve-loc?ref=<LAST_LOC_ID> it works and I can continue. I assume it might be a frontend problem, so I will link an issue there.

**Comment by ice09** [comment]
After the last commit/merge of 07/11 the application is not working with the Web-frontend anymore, this seems to be related to port changes but can have other causes as well. Is the demo application assumed to work still? Otherwise, a decprecation remark would be helpful to avoid others wasting time trying to get the showcase running.
However, I'd strongly advise to get the showcase running again, it's a great and very useful showcase for the capabilities of Corda and it's differences from public chains like Ethereum and also for the strengths of Corda for certain use cases like supply chains.

**Comment by joeldudleyr3** [comment]
Thanks ice09, looking into it.

**Comment by AN8991** [comment]
Still not working as of September. The Data flow of Transaction has stopped and the Letter of Credit cannot be called for since the Transaction data is always blank.
